name: Build and Run Spring Boot App in Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t app-auth:latest .

      - name: Restart Docker container
        shell: powershell
        run: |
          $containerName = "springboot-app"
          $existingContainer = docker ps -aq --filter "name=^/$containerName$"

          if ($existingContainer) {
            docker rm -f $containerName
          }

          docker run -d --name $containerName -p 8080:8080 --restart unless-stopped app-auth:latest
