name: Build and Run Spring Boot App in Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t springboot-app:latest .

      - name: Stop old container
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true

      - name: Run new container
        run: |
          docker run -d \
            --name springboot-app \
            -p 8080:8080 \
            springboot-app:latest